### ISSUE TITLE
Doesn't work for webstorm 2017.2 in ubuntu

### ISSUE THREAD

**Issue by bhavyaw1** [blakedietz/js-live-template#5]
How can we make it work in webstorm 2017.2 in ubuntu.

**Comment by blakedietz** [comment]
Sorry for the delay on this. I'll see if I can take a look as to why it's not working for that platform.

**Comment by chenop** [comment]
Confirm this is not working for Webstorm 2017.2 windows as well

**Comment by blakedietz** [comment]
Ok, perhaps this needs to be updated. I'll actually take a look this time around.

**Comment by nesvand** [comment]
I believe this is also affecting IntelliJ 2017.2 as well (tested on MacOS version)

I might try to replicate one of the live templates to compare how they're exported

**Comment by nesvand** [comment]
Ignore my comment - instead of using the settings.jar I created a Live Template group called `es6` and copied the `es6.xml` to the templates folder in the app settings. Working as expected 👍

**Comment by theoutlander** [comment]
JAR file didn't work for me on 2017.3, but es6.xml file worked.
